### ISSUE TITLE
command is null when calling neuron-manage

### ISSUE THREAD

**Issue by jbroudou** [dfinity/quill#97] opened 2022-02-08 01:14 UTC
Issuing this command and sending the resulting JSON payload
```
./target/release/quill neuron-manage --split AMOUNT NEURON_ID
```

results in command = null

```
Sending message with

  Call type:   update
  Sender:      PRINCIPAL_ID
  Canister id: rrkah-fqaaa-aaaaa-aaaaq-cai
  Method name: manage_neuron
  Arguments:   (
  record {
    id = opt record { id = NEURON_ID : nat64 };
    command = null;
    neuron_id_or_subaccount = null;
  },
)
```

This then returns an error from the IC

```
The Replica returned an error: code 5, message: "Canister rrkah-fqaaa-aaaaa-aaaaq-cai trapped explicitly: Panicked at 'explicit panic', /ic/rs/nns/governance/src/governance.rs:5949:21"
```

I get this problem with any neuron-manage sub-command.

**Comment by adamspofford-dfinity** [comment] 2023-03-02 00:51
Fixed in an unknown PR, caused by candid file mismatch.

**Closed by adamspofford-dfinity** 2023-03-02 00:51 UTC
